language: python
python:
  #- "2.6"
  #- "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  - "3.5"
before_install:
    - pip install --upgrade pip
    - pip install pytest pytest-cov
    - pip install codecov
# command to install dependencies
#install: "pip install -r requirements.txt"
#before_script:
#  - cd tests
# command to run tests
script: py.test -v --cov=asserted tests --cov-report term-missing
after_success:
    - codecov
